export interface Project {
  slug: string
  title: string
  date: string
  borough?: string
  neighborhood?: string
  services: string[]
  materials?: string[]
  hardware?: string[]
  durationRange?: string
  priceRange?: string
  scenarioType: 'real' | 'typical'
  excerpt: string
  image: string
  imageAlt: string
}

export const projects: Project[] = [
  {
    slug: 'frameless-shower-door-cost-nyc',
    title: 'Frameless Shower Door Cost in NYC: What Actually Changes the Price',
    date: '2026-05-09',
    services: ['Frameless Shower Doors', 'Buyer Guide'],
    materials: ['3/8" tempered glass', '1/2" tempered glass'],
    scenarioType: 'typical',
    excerpt: 'A practical buyer guide to NYC frameless shower door pricing, layout choices, hardware, glass thickness, and building coordination.',
    image: '/editorial/configurations/door-fixed-panel.jpg',
    imageAlt: 'Frameless shower door and fixed panel configuration with satin brass hardware',
  },

  {
    slug: 'metroglasspro-project-20260418-072239',
    title: 'Matte Black Inline Shower Door for a Finished Tile Bathroom',
    date: '2026-04-18',
    services: ['Frameless Shower Doors', 'Inline Shower Door', 'Matte Black Hardware'],
    materials: ['3/8" clear tempered glass'],
    hardware: ['Matte black hinges', 'Square pull handle'],
    durationRange: '5 to 7 business days',
    scenarioType: 'real',
    excerpt: 'A clean inline frameless shower door planned around finished tile, tight reveals, and matte black hardware for a sharper NYC bathroom renovation.',
    image: '/gallery/mgp-20260418-072239-1-823776a3-3e11-43a8-afdd-49d1e25bfb45.png',
    imageAlt: 'Inline frameless shower door with matte black hardware in a finished NYC tile bathroom',
  },

  {
    slug: 'metroglasspro-project-20260417-072240',
    title: 'Tub-to-Shower Glass Upgrade With Chrome Hardware',
    date: '2026-04-17',
    services: ['Tub Shower Glass', 'Frameless Shower Doors', 'Chrome Hardware'],
    materials: ['Clear tempered glass'],
    hardware: ['Chrome hinges', 'Chrome pull handle'],
    durationRange: '5 to 7 business days',
    scenarioType: 'real',
    excerpt: 'A tub-shower glass upgrade that replaces visual clutter with clear tempered glass, chrome hardware, and a cleaner bathroom sightline.',
    image: '/gallery/mgp-20260417-072240-1-photo-2026-03-19-20-41-48-7.jpg',
    imageAlt: 'Frameless tub shower glass with chrome hardware in a renovated NYC bathroom',
  },

  {
    slug: 'metroglasspro-project-20260416-072239',
    title: 'Tight Alcove Shower Door With Clean Reveal Lines',
    date: '2026-04-16',
    services: ['Alcove Shower Door', 'Frameless Shower Doors'],
    materials: ['3/8" clear tempered glass'],
    hardware: ['Chrome hinges', 'Wall-mounted handle'],
    durationRange: '5 to 7 business days',
    scenarioType: 'real',
    excerpt: 'A compact alcove shower door measured for even reveals, reliable swing clearance, and a bright frameless look in a NYC apartment bath.',
    image: '/gallery/mgp-20260416-072239-1-photo-2026-03-19-20-32-22-9.jpg',
    imageAlt: 'Compact alcove frameless shower door with clean reveal lines in NYC',
  },

  {
    slug: 'metroglasspro-project-20260415-072237',
    title: 'Low-Iron Glass Enclosure for a Bright Primary Bath',
    date: '2026-04-15',
    services: ['Low-Iron Shower Glass', 'Frameless Shower Enclosure'],
    materials: ['Low-iron tempered glass'],
    hardware: ['Polished chrome hardware'],
    durationRange: '5 to 7 business days',
    scenarioType: 'real',
    excerpt: 'A brighter frameless shower enclosure using low-iron glass to keep the tile color clear and reduce the green cast of standard glass.',
    image: '/gallery/mgp-20260415-072237-1-56bcf70c-7086-45d9-8eb4-c66daca1820f.png',
    imageAlt: 'Low-iron frameless shower glass enclosure in a bright NYC primary bathroom',
  },

  {
    slug: 'metroglasspro-project-20260414-072247',
    title: 'Corner Shower Glass With a Fixed Panel Return',
    date: '2026-04-14',
    services: ['Corner Shower Enclosure', 'Door and Fixed Panel'],
    materials: ['Clear tempered glass'],
    hardware: ['Chrome clips', 'Chrome hinges'],
    durationRange: '5 to 7 business days',
    scenarioType: 'real',
    excerpt: 'A corner shower enclosure with a fixed return panel, built to keep the entry open while controlling splash in a compact NYC bathroom.',
    image: '/gallery/mgp-20260414-072247-1-06a3cca1-5cb7-4b71-8a42-18ab9d6af8e5.jpg',
    imageAlt: 'Corner frameless shower enclosure with door and fixed return panel in NYC',
  },

  {
    slug: 'metroglasspro-project-20260413-072255',
    title: 'Minimal Walk-In Shower Panel for an Open Layout',
    date: '2026-04-13',
    services: ['Walk-In Shower Panel', 'Frameless Shower Glass'],
    materials: ['Clear tempered glass'],
    hardware: ['Wall clips', 'Stabilizer bar'],
    durationRange: '5 to 7 business days',
    scenarioType: 'real',
    excerpt: 'A single frameless walk-in panel that keeps the bathroom open while adding splash control and a finished architectural edge.',
    image: '/gallery/mgp-20260413-072255-1-9617e461-ebcd-4d53-8022-1a21c7eb36d7.jpg',
    imageAlt: 'Minimal frameless walk-in shower panel with wall clips in NYC bathroom',
  },

  {
    slug: 'metroglasspro-project-20260412-072239',
    title: 'Chrome Frameless Door With Precise Curb Alignment',
    date: '2026-04-12',
    services: ['Frameless Shower Door', 'Chrome Hardware'],
    materials: ['3/8" clear tempered glass'],
    hardware: ['Chrome hinges', 'Chrome handle'],
    durationRange: '5 to 7 business days',
    scenarioType: 'real',
    excerpt: 'A frameless shower door aligned to the finished curb and wall conditions for a clean seal, smooth swing, and polished chrome finish.',
    image: '/gallery/mgp-20260412-072239-1-1bd0dc04-d72d-4d5b-8e98-0236a10419e0.jpg',
    imageAlt: 'Chrome frameless shower door aligned to a finished shower curb in NYC',
  },

  {
    slug: 'metroglasspro-project-20260411-072241',
    title: 'Apartment Shower Door Replacement After Tile Work',
    date: '2026-04-11',
    services: ['Shower Door Replacement', 'Frameless Shower Doors'],
    materials: ['Clear tempered glass'],
    hardware: ['Chrome hardware'],
    durationRange: '5 to 7 business days',
    scenarioType: 'real',
    excerpt: 'A post-tile shower door replacement for an apartment bath, measured around finished surfaces instead of relying on rough opening assumptions.',
    image: '/gallery/mgp-20260411-072241-1-6d0eda8f-bb16-4b51-a973-dd973b61afcf.jpg',
    imageAlt: 'Apartment shower door replacement with clear frameless glass in NYC',
  },

  {
    slug: 'metroglasspro-project-20260410-072239',
    title: 'Sliding Bypass Shower Door for a Narrow NYC Bath',
    date: '2026-04-10',
    services: ['Sliding Shower Doors', 'Bypass Shower Glass'],
    materials: ['Clear tempered glass'],
    hardware: ['Chrome bypass track', 'Towel bar handles'],
    durationRange: '5 to 7 business days',
    scenarioType: 'real',
    excerpt: 'A sliding bypass shower door chosen for a narrow bathroom where a swing door would crowd the vanity and daily circulation.',
    image: '/gallery/mgp-20260410-072239-1-4bfdebce-b0ef-4abd-9dc6-77351d23029d.jpg',
    imageAlt: 'Sliding bypass shower door with chrome track in a narrow NYC bathroom',
  },

  {
    slug: 'metroglasspro-project-20260409-072238',
    title: 'Door and Notched Panel for a Compact Renovation',
    date: '2026-04-09',
    services: ['Door and Panel Shower Glass', 'Custom Notched Glass'],
    materials: ['Clear tempered glass'],
    hardware: ['Chrome clamps', 'Chrome hinges'],
    durationRange: '5 to 7 business days',
    scenarioType: 'real',
    excerpt: 'A compact bathroom enclosure using a custom notched panel to work around field conditions while keeping the frameless look clean.',
    image: '/gallery/mgp-20260409-072238-1-d8fea6b2-dc36-4f11-b584-2ce5ea25c082.jpg',
    imageAlt: 'Custom notched shower glass panel with frameless door in a compact NYC renovation',
  },

  {
    slug: 'metroglasspro-project-20260408-072238',
    title: 'Satin Brass Shower Glass Detail for a Designer Bathroom',
    date: '2026-04-08',
    services: ['Designer Shower Glass', 'Frameless Shower Doors'],
    materials: ['Clear tempered glass'],
    hardware: ['Satin brass hardware'],
    durationRange: '5 to 7 business days',
    scenarioType: 'real',
    excerpt: 'A designer-friendly shower glass installation using satin brass hardware, precise alignment, and clean sightlines against finished tile.',
    image: '/gallery/mgp-20260408-072238-1-da9fa6d1-d76b-4c73-8f3b-ba412c82d072.png',
    imageAlt: 'Frameless shower glass with satin brass hardware in a designer NYC bathroom',
  },

  {
    slug: 'metroglasspro-project-20260407-072313',
    title: 'Prewar Bathroom Shower Glass With Out-of-Plumb Walls',
    date: '2026-04-07',
    services: ['Custom Shower Glass', 'Frameless Shower Doors'],
    materials: ['Clear tempered glass'],
    hardware: ['Chrome hardware'],
    durationRange: '5 to 7 business days',
    scenarioType: 'real',
    excerpt: 'A custom shower glass installation planned for older NYC wall conditions, where out-of-plumb surfaces required real field measurement.',
    image: '/gallery/mgp-20260407-072313-1-img-2199.png',
    imageAlt: 'Custom frameless shower glass installed against older out-of-plumb NYC bathroom walls',
  },

  {
    slug: 'metroglasspro-project-20260406-072239',
    title: 'Clean-Lined Frameless Door After Contractor Tile Prep',
    date: '2026-04-06',
    services: ['Frameless Shower Door', 'Contractor Coordination'],
    materials: ['Clear tempered glass'],
    hardware: ['Chrome hinges', 'Chrome handle'],
    durationRange: '5 to 7 business days',
    scenarioType: 'real',
    excerpt: 'A frameless shower door installed after contractor tile prep, with final measurements used to catch the real opening before fabrication.',
    image: '/gallery/mgp-20260406-072239-1-photo-2026-03-16-20-26-43.jpg',
    imageAlt: 'Clean-lined frameless shower door installed after contractor tile prep in NYC',
  },

  {
    slug: 'metroglasspro-project-20260405-072237',
    title: 'Small Bathroom Glass Enclosure With Better Light Flow',
    date: '2026-04-05',
    services: ['Small Bathroom Shower Glass', 'Frameless Shower Enclosure'],
    materials: ['Clear tempered glass'],
    hardware: ['Chrome hardware'],
    durationRange: '5 to 7 business days',
    scenarioType: 'real',
    excerpt: 'A compact bathroom glass enclosure designed to reduce visual weight, improve light flow, and make the shower feel less closed in.',
    image: '/gallery/mgp-20260405-072237-1-photo-2026-03-19-12-55-48-2.jpg',
    imageAlt: 'Small NYC bathroom shower glass enclosure with clear frameless panels',
  },

  {
    slug: 'metroglasspro-project-20260404-072241',
    title: 'Tub Shield and Door Planning for a NYC Apartment',
    date: '2026-04-04',
    services: ['Tub Shield', 'Shower Door Planning'],
    materials: ['Clear tempered glass'],
    hardware: ['Chrome hardware'],
    durationRange: '5 to 7 business days',
    scenarioType: 'real',
    excerpt: 'A NYC apartment bath planned around a lighter tub glass solution, balancing splash control, access, and a cleaner finished look.',
    image: '/gallery/mgp-20260404-072241-1-photo-2026-03-16-21-38-47.jpg',
    imageAlt: 'Clear tub shield and shower door planning in a NYC apartment bathroom',
  },

  {
    slug: 'metroglasspro-project-20260403-072242',
    title: 'Shower Glass Installed After Final Tile Measurements',
    date: '2026-04-03',
    services: ['Post-Tile Measurement', 'Frameless Shower Glass'],
    materials: ['Clear tempered glass'],
    hardware: ['Chrome hardware'],
    durationRange: '5 to 7 business days',
    scenarioType: 'real',
    excerpt: 'A frameless shower glass project where final post-tile measurements protected the fit, reveal lines, and hardware placement.',
    image: '/gallery/mgp-20260403-072242-1-photo-2026-03-16-13-26-17.jpg',
    imageAlt: 'Frameless shower glass installed after final tile measurements in NYC',
  },

  {
    slug: 'metroglasspro-project-20260402-010336',
    title: 'Multi-Panel Custom Shower Glass Installation in NYC',
    date: '2026-04-02',
    services: ['Multi-Panel Shower Glass', 'Custom Frameless Enclosure'],
    materials: ['Clear tempered glass'],
    hardware: ['Chrome clips', 'Chrome hinges'],
    durationRange: '5 to 7 business days',
    scenarioType: 'real',
    excerpt: 'A multi-panel custom shower glass installation built around the actual finished opening, with clear glass and minimal chrome hardware.',
    image: '/gallery/mgp-20260402-010336-1-photo-2026-03-23-15-18-21.jpg',
    imageAlt: 'Multi-panel custom frameless shower glass installation in NYC bathroom',
  },

  {
    slug: 'visualize-shower-door-options-nyc',
    title: 'We Show You Every Option Before Any Glass Gets Cut',
    date: '2026-04-01',
    services: ['Frameless Shower Doors', 'Design Consultation', 'Neo-Angle Enclosure'],
    materials: ['3/8" clear tempered glass'],
    hardware: ['Chrome sliding hardware', 'Chrome hinges'],
    durationRange: '5 to 7 business days',
    scenarioType: 'real',
    excerpt: 'Before any glass is fabricated, we render your actual bathroom with four enclosure configurations, hinged, sliding, corner, and neo-angle, so you choose with full confidence. This is the Visualize process.',
    image: '/gallery/visualize-feature-neo-angle.jpg',
    imageAlt: 'Neo-angle curved frameless shower enclosure with chrome hardware in a compact NYC bathroom with white marble tile',
  },
  {
    slug: '84-clinton-lower-east-side-shower-door-before-after',
    title: '84 Clinton Shower Door Before and After, Lower East Side Manhattan',
    date: '2026-03-16',
    borough: 'Manhattan',
    neighborhood: 'Lower East Side',
    services: ['Sliding Shower Doors', 'Frameless Shower Doors'],
    hardware: ['Chrome sliding hardware', 'Towel bar handles'],
    scenarioType: 'real',
    excerpt: 'A before and after shower door setup at 84 Clinton, Lower East Side Manhattan, showing how a compact bathroom can feel brighter, cleaner, and more finished with a custom sliding glass enclosure.',
    image: '/gallery/84-clinton-after-preview.jpg',
    imageAlt: 'Completed sliding shower door at 84 Clinton in the Lower East Side, Manhattan',
  },
  {
    slug: 'interior-design-collaboration-shower-door-nyc',
    title: 'Why It Matters Who You Hire: A Glass Install Gone Wrong — and How We Fixed It',
    date: '2026-03-11',
    services: ['Frameless Shower Doors', 'Contractor Remediation'],
    hardware: ['Chrome hardware', '3/8" glass clips'],
    scenarioType: 'real',
    excerpt: 'An interior design firm\'s previous contractor used the wrong clips, botched the silicone, and ghosted his own warranty. We fixed it — and gained a long-term design partner.',
    image: '/gallery/jakob-interior-design-collaboration-desktop.jpg',
    imageAlt: 'Frameless tub enclosure with chrome hardware against white marble tile — remediated NYC project',
  },
  {
    slug: 'shower-glass-design-consultation-nyc',
    title: 'We Design Before We Install: Shower Glass Consultation for Architects and Designers',
    date: '2026-03-11',
    services: ['Frameless Shower Doors', 'Design Consultation'],
    hardware: ['CRL hinges', 'U-channel', 'Glass-to-glass clamps', 'Barn-door track'],
    scenarioType: 'real',
    excerpt: 'We render multiple enclosure configurations — swing, sliding, fixed panel — in your client\'s actual bathroom with hardware finish comparisons before fabrication begins.',
    image: '/editorial/design-process-sketch.jpg',
    imageAlt: 'Shower glass design sketch showing bathroom configuration renders on tablet with hardware finish annotations',
  },
  {
    slug: 'coop-condo-shower-door-installation-nyc',
    title: 'Co-op & Condo Shower Door Installation in NYC: What You Need to Know',
    date: '2026-03-11',
    services: ['Frameless Shower Doors', 'Building Coordination'],
    hardware: ['Wall-mount hinges', 'U-channel', 'Sleeve anchors'],
    scenarioType: 'real',
    excerpt: 'Everything NYC co-op and condo owners need to know: COI requirements, freight elevator scheduling, quiet hours, alteration agreements, and pre-war building considerations.',
    image: '/editorial/shower-door.jpg',
    imageAlt: 'Frameless shower door installed in a NYC co-op apartment',
  },
  {
    slug: 'single-swing-door-nyc',
    title: 'Single Swing Frameless Shower Door: NYC\'s Most Popular Configuration',
    date: '2026-02-23',
    services: ['Frameless Shower Doors'],
    hardware: ['Wall-mount hinges', 'Pivot hinges'],
    scenarioType: 'real',
    excerpt: 'Why the single swing door is NYC\'s #1 shower configuration — glass thickness, swing direction, and what makes it ideal for apartments.',
    image: '/editorial/configurations/single-swing-door.jpg',
    imageAlt: 'Single swing frameless shower door with satin brass hinges',
  },
  {
    slug: 'door-fixed-panel-nyc',
    title: 'Door + Fixed Panel: The Go-To for Wider NYC Shower Openings',
    date: '2026-02-23',
    services: ['Frameless Shower Doors'],
    hardware: ['Glass-to-glass clamps', 'U-channel', 'Support bar'],
    scenarioType: 'real',
    excerpt: 'When your opening exceeds 36", you need a fixed panel. NYC tub-to-shower conversions, hardware matching, and sizing guide.',
    image: '/editorial/configurations/door-fixed-panel.jpg',
    imageAlt: 'Frameless door plus fixed glass panel with satin brass hardware',
  },
  {
    slug: 'sliding-bypass-doors-nyc',
    title: 'Sliding Bypass Frameless Doors: When There\'s No Room to Swing',
    date: '2026-02-23',
    services: ['Frameless Shower Doors'],
    hardware: ['Barn-door track', 'Top-hung rollers'],
    scenarioType: 'real',
    excerpt: 'Frameless bypass doors for NYC tub-shower combos. Cost vs framed sliders, maintenance tips, and when this is the right choice.',
    image: '/editorial/configurations/sliding-bypass-doors.jpg',
    imageAlt: 'Frameless sliding bypass shower door with satin brass track hardware',
  },
  {
    slug: '90-corner-enclosure-nyc',
    title: '90° Corner Enclosure: The Luxury Standard for NYC Showers',
    date: '2026-02-23',
    services: ['Frameless Shower Doors'],
    hardware: ['Glass-to-glass 90° clamp', 'Wall-mount hinges'],
    scenarioType: 'real',
    excerpt: 'Two glass walls at 90° — the luxury standard. Why corners work in tight NYC bathrooms and what the cost premium looks like.',
    image: '/editorial/configurations/90-corner-enclosure.jpg',
    imageAlt: '90-degree corner frameless glass enclosure with satin brass hinge',
  },
  {
    slug: 'neo-angle-enclosure-nyc',
    title: 'Neo-Angle Enclosure: Solving NYC\'s Odd-Shaped Shower Bases',
    date: '2026-02-23',
    services: ['Frameless Shower Doors'],
    hardware: ['Angled clamps', 'Multi-point connectors'],
    scenarioType: 'real',
    excerpt: 'Built for non-standard and angled bases common in pre-war NYC buildings. How the 3-panel geometry maximizes space.',
    image: '/editorial/configurations/neo-angle-enclosure.jpg',
    imageAlt: 'Neo-angle frameless glass enclosure overhead view with brass clamps',
  },
  {
    slug: 'walk-in-shower-panel-nyc',
    title: 'Walk-In Shower Panel: The Wet Room Look Taking Over NYC',
    date: '2026-02-23',
    services: ['Frameless Shower Doors'],
    hardware: ['Wall clamps'],
    scenarioType: 'real',
    excerpt: 'No door, just a fixed panel. The most premium shower look in NYC — and what waterproofing it requires.',
    image: '/editorial/configurations/walk-in-panel.jpg',
    imageAlt: 'Walk-in frameless glass shower panel with satin brass wall clamps',
  },
  {
    slug: 'typical-mirror-replacement-nyc',
    title: 'Mirror Replacement in a NYC Apartment: What to Expect',
    date: '2026-02-15',
    services: ['Custom Mirrors', 'Mirror Installation'],
    materials: ['1/4" flat polished mirror', 'J-channel mounting'],
    durationRange: '1–2 hours',
    priceRange: '$200–$800',
    scenarioType: 'typical',
    excerpt: 'A walkthrough of what a typical mirror replacement looks like in a New York City apartment — from measurement to install.',
    image: '/gallery/mirror-cabinet-blue-tape.jpg',
    imageAlt: 'Medicine cabinet mirror with blue tape during silicone curing in NYC apartment',
  },
  {
    slug: 'crl-geneva-vs-vienna-hinges',
    title: 'CRL Geneva vs Vienna Hinges: A High-Level Comparison',
    date: '2026-02-18',
    services: ['Frameless Shower Doors'],
    hardware: ['CRL Geneva hinge', 'CRL Vienna hinge'],
    scenarioType: 'real',
    excerpt: 'Two of the most popular frameless shower door hinges compared — when to use each, and why it matters for your installation.',
    image: '/editorial/tools.jpg',
    imageAlt: 'Shower door hardware and installation tools',
  },
]
