export interface Project {
  slug: string
  title: string
  date: string
  borough?: string
  neighborhood?: string
  services: string[]
  materials?: string[]
  hardware?: string[]
  durationRange?: string
  priceRange?: string
  scenarioType: 'real' | 'typical'
  excerpt: string
  image: string
  imageAlt: string
}

export const projects: Project[] = [
  {
    slug: 'metroglasspro-project-20260418-072239',
    title: 'Custom Glass Installation — MetroGlass Pro NYC',
    date: '2026-04-18',
    services: ['Frameless Shower Doors'],
    scenarioType: 'real',
    excerpt: 'A recent custom frameless shower enclosure installation by MetroGlass Pro in NYC. Precision field measurements, chrome hardware, and a fast turnaround from approval to install.',
    image: '/gallery/mgp-20260418-072239-1-823776a3-3e11-43a8-afdd-49d1e25bfb45.png',
    imageAlt: 'Custom frameless shower enclosure installed by MetroGlass Pro NYC',
  },

  {
    slug: 'metroglasspro-project-20260417-072240',
    title: 'Custom Glass Installation — MetroGlass Pro NYC',
    date: '2026-04-17',
    services: ['Frameless Shower Doors'],
    scenarioType: 'real',
    excerpt: 'A recent custom frameless shower enclosure installation by MetroGlass Pro in NYC. Precision field measurements, chrome hardware, and a fast turnaround from approval to install.',
    image: '/gallery/mgp-20260417-072240-1-photo-2026-03-19-20-41-48-7.jpg',
    imageAlt: 'Custom frameless shower enclosure installed by MetroGlass Pro NYC',
  },

  {
    slug: 'metroglasspro-project-20260416-072239',
    title: 'Custom Glass Installation — MetroGlass Pro NYC',
    date: '2026-04-16',
    services: ['Frameless Shower Doors'],
    scenarioType: 'real',
    excerpt: 'A recent custom frameless shower enclosure installation by MetroGlass Pro in NYC. Precision field measurements, chrome hardware, and a fast turnaround from approval to install.',
    image: '/gallery/mgp-20260416-072239-1-photo-2026-03-19-20-32-22-9.jpg',
    imageAlt: 'Custom frameless shower enclosure installed by MetroGlass Pro NYC',
  },

  {
    slug: 'metroglasspro-project-20260415-072237',
    title: 'Custom Glass Installation — MetroGlass Pro NYC',
    date: '2026-04-15',
    services: ['Frameless Shower Doors'],
    scenarioType: 'real',
    excerpt: 'A recent custom frameless shower enclosure installation by MetroGlass Pro in NYC. Precision field measurements, chrome hardware, and a fast turnaround from approval to install.',
    image: '/gallery/mgp-20260415-072237-1-56bcf70c-7086-45d9-8eb4-c66daca1820f.png',
    imageAlt: 'Custom frameless shower enclosure installed by MetroGlass Pro NYC',
  },

  {
    slug: 'metroglasspro-project-20260414-072247',
    title: 'Custom Glass Installation — MetroGlass Pro NYC',
    date: '2026-04-14',
    services: ['Frameless Shower Doors'],
    scenarioType: 'real',
    excerpt: 'A recent custom frameless shower enclosure installation by MetroGlass Pro in NYC. Precision field measurements, chrome hardware, and a fast turnaround from approval to install.',
    image: '/gallery/mgp-20260414-072247-1-06a3cca1-5cb7-4b71-8a42-18ab9d6af8e5.jpg',
    imageAlt: 'Custom frameless shower enclosure installed by MetroGlass Pro NYC',
  },

  {
    slug: 'metroglasspro-project-20260413-072255',
    title: 'Custom Glass Installation — MetroGlass Pro NYC',
    date: '2026-04-13',
    services: ['Frameless Shower Doors'],
    scenarioType: 'real',
    excerpt: 'A recent custom frameless shower enclosure installation by MetroGlass Pro in NYC. Precision field measurements, chrome hardware, and a fast turnaround from approval to install.',
    image: '/gallery/mgp-20260413-072255-1-9617e461-ebcd-4d53-8022-1a21c7eb36d7.jpg',
    imageAlt: 'Custom frameless shower enclosure installed by MetroGlass Pro NYC',
  },

  {
    slug: 'metroglasspro-project-20260412-072239',
    title: 'Custom Glass Installation — MetroGlass Pro NYC',
    date: '2026-04-12',
    services: ['Frameless Shower Doors'],
    scenarioType: 'real',
    excerpt: 'A recent custom frameless shower enclosure installation by MetroGlass Pro in NYC. Precision field measurements, chrome hardware, and a fast turnaround from approval to install.',
    image: '/gallery/mgp-20260412-072239-1-1bd0dc04-d72d-4d5b-8e98-0236a10419e0.jpg',
    imageAlt: 'Custom frameless shower enclosure installed by MetroGlass Pro NYC',
  },

  {
    slug: 'metroglasspro-project-20260411-072241',
    title: 'Custom Glass Installation — MetroGlass Pro NYC',
    date: '2026-04-11',
    services: ['Frameless Shower Doors'],
    scenarioType: 'real',
    excerpt: 'A recent custom frameless shower enclosure installation by MetroGlass Pro in NYC. Precision field measurements, chrome hardware, and a fast turnaround from approval to install.',
    image: '/gallery/mgp-20260411-072241-1-6d0eda8f-bb16-4b51-a973-dd973b61afcf.jpg',
    imageAlt: 'Custom frameless shower enclosure installed by MetroGlass Pro NYC',
  },

  {
    slug: 'metroglasspro-project-20260410-072239',
    title: 'Custom Glass Installation — MetroGlass Pro NYC',
    date: '2026-04-10',
    services: ['Frameless Shower Doors'],
    scenarioType: 'real',
    excerpt: 'A recent custom frameless shower enclosure installation by MetroGlass Pro in NYC. Precision field measurements, chrome hardware, and a fast turnaround from approval to install.',
    image: '/gallery/mgp-20260410-072239-1-4bfdebce-b0ef-4abd-9dc6-77351d23029d.jpg',
    imageAlt: 'Custom frameless shower enclosure installed by MetroGlass Pro NYC',
  },

  {
    slug: 'metroglasspro-project-20260409-072238',
    title: 'Custom Glass Installation — MetroGlass Pro NYC',
    date: '2026-04-09',
    services: ['Frameless Shower Doors'],
    scenarioType: 'real',
    excerpt: 'A recent custom frameless shower enclosure installation by MetroGlass Pro in NYC. Precision field measurements, chrome hardware, and a fast turnaround from approval to install.',
    image: '/gallery/mgp-20260409-072238-1-d8fea6b2-dc36-4f11-b584-2ce5ea25c082.jpg',
    imageAlt: 'Custom frameless shower enclosure installed by MetroGlass Pro NYC',
  },

  {
    slug: 'metroglasspro-project-20260408-072238',
    title: 'Custom Glass Installation — MetroGlass Pro NYC',
    date: '2026-04-08',
    services: ['Frameless Shower Doors'],
    scenarioType: 'real',
    excerpt: 'A recent custom frameless shower enclosure installation by MetroGlass Pro in NYC. Precision field measurements, chrome hardware, and a fast turnaround from approval to install.',
    image: '/gallery/mgp-20260408-072238-1-da9fa6d1-d76b-4c73-8f3b-ba412c82d072.png',
    imageAlt: 'Custom frameless shower enclosure installed by MetroGlass Pro NYC',
  },

  {
    slug: 'metroglasspro-project-20260407-072313',
    title: 'Custom Glass Installation — MetroGlass Pro NYC',
    date: '2026-04-07',
    services: ['Frameless Shower Doors'],
    scenarioType: 'real',
    excerpt: 'A recent custom frameless shower enclosure installation by MetroGlass Pro in NYC. Precision field measurements, chrome hardware, and a fast turnaround from approval to install.',
    image: '/gallery/mgp-20260407-072313-1-img-2199.png',
    imageAlt: 'Custom frameless shower enclosure installed by MetroGlass Pro NYC',
  },

  {
    slug: 'metroglasspro-project-20260406-072239',
    title: 'Custom Glass Installation — MetroGlass Pro NYC',
    date: '2026-04-06',
    services: ['Frameless Shower Doors'],
    scenarioType: 'real',
    excerpt: 'A recent custom frameless shower enclosure installation by MetroGlass Pro in NYC. Precision field measurements, chrome hardware, and a fast turnaround from approval to install.',
    image: '/gallery/mgp-20260406-072239-1-photo-2026-03-16-20-26-43.jpg',
    imageAlt: 'Custom frameless shower enclosure installed by MetroGlass Pro NYC',
  },

  {
    slug: 'metroglasspro-project-20260405-072237',
    title: 'Custom Glass Installation — MetroGlass Pro NYC',
    date: '2026-04-05',
    services: ['Frameless Shower Doors'],
    scenarioType: 'real',
    excerpt: 'A recent custom frameless shower enclosure installation by MetroGlass Pro in NYC. Precision field measurements, chrome hardware, and a fast turnaround from approval to install.',
    image: '/gallery/mgp-20260405-072237-1-photo-2026-03-19-12-55-48-2.jpg',
    imageAlt: 'Custom frameless shower enclosure installed by MetroGlass Pro NYC',
  },

  {
    slug: 'metroglasspro-project-20260404-072241',
    title: 'Custom Glass Installation — MetroGlass Pro NYC',
    date: '2026-04-04',
    services: ['Frameless Shower Doors'],
    scenarioType: 'real',
    excerpt: 'A recent custom frameless shower enclosure installation by MetroGlass Pro in NYC. Precision field measurements, chrome hardware, and a fast turnaround from approval to install.',
    image: '/gallery/mgp-20260404-072241-1-photo-2026-03-16-21-38-47.jpg',
    imageAlt: 'Custom frameless shower enclosure installed by MetroGlass Pro NYC',
  },

  {
    slug: 'metroglasspro-project-20260403-072242',
    title: 'Custom Glass Installation — MetroGlass Pro NYC',
    date: '2026-04-03',
    services: ['Frameless Shower Doors'],
    scenarioType: 'real',
    excerpt: 'A recent custom frameless shower enclosure installation by MetroGlass Pro in NYC. Precision field measurements, chrome hardware, and a fast turnaround from approval to install.',
    image: '/gallery/mgp-20260403-072242-1-photo-2026-03-16-13-26-17.jpg',
    imageAlt: 'Custom frameless shower enclosure installed by MetroGlass Pro NYC',
  },

  {
    slug: 'metroglasspro-project-20260402-072239',
    title: 'Custom Glass Installation — MetroGlass Pro NYC',
    date: '2026-04-02',
    services: ['Frameless Shower Doors'],
    scenarioType: 'real',
    excerpt: 'A recent custom frameless shower enclosure installation by MetroGlass Pro in NYC. Precision field measurements, chrome hardware, and a fast turnaround from approval to install.',
    image: '/gallery/mgp-20260402-072239-1-photo-2026-03-10-17-24-40.jpg',
    imageAlt: 'Custom frameless shower enclosure installed by MetroGlass Pro NYC',
  },

  {
    slug: 'metroglasspro-project-20260402-010336',
    title: 'Custom Glass Installation — MetroGlass Pro NYC',
    date: '2026-04-02',
    services: ['Frameless Shower Doors'],
    scenarioType: 'real',
    excerpt: 'A recent custom frameless shower enclosure installation by MetroGlass Pro in NYC. Precision field measurements, chrome hardware, and a fast turnaround from approval to install.',
    image: '/gallery/mgp-20260402-010336-1-photo-2026-03-23-15-18-21.jpg',
    imageAlt: 'Custom frameless shower enclosure installed by MetroGlass Pro NYC',
  },

  {
    slug: 'visualize-shower-door-options-nyc',
    title: 'We Show You Every Option Before Any Glass Gets Cut',
    date: '2026-04-01',
    services: ['Frameless Shower Doors', 'Design Consultation', 'Neo-Angle Enclosure'],
    materials: ['3/8" clear tempered glass'],
    hardware: ['Chrome sliding hardware', 'Chrome hinges'],
    durationRange: '5 to 7 business days',
    scenarioType: 'real',
    excerpt: 'Before any glass is fabricated, we render your actual bathroom with four enclosure configurations, hinged, sliding, corner, and neo-angle, so you choose with full confidence. This is the Visualize process.',
    image: '/gallery/visualize-feature-neo-angle.jpg',
    imageAlt: 'Neo-angle curved frameless shower enclosure with chrome hardware in a compact NYC bathroom with white marble tile',
  },
  {
    slug: '84-clinton-lower-east-side-shower-door-before-after',
    title: '84 Clinton Shower Door Before and After, Lower East Side Manhattan',
    date: '2026-03-16',
    borough: 'Manhattan',
    neighborhood: 'Lower East Side',
    services: ['Sliding Shower Doors', 'Frameless Shower Doors'],
    hardware: ['Chrome sliding hardware', 'Towel bar handles'],
    scenarioType: 'real',
    excerpt: 'A before and after shower door setup at 84 Clinton, Lower East Side Manhattan, showing how a compact bathroom can feel brighter, cleaner, and more finished with a custom sliding glass enclosure.',
    image: '/gallery/84-clinton-after-preview.jpg',
    imageAlt: 'Completed sliding shower door at 84 Clinton in the Lower East Side, Manhattan',
  },
  {
    slug: 'interior-design-collaboration-shower-door-nyc',
    title: 'Why It Matters Who You Hire: A Glass Install Gone Wrong — and How We Fixed It',
    date: '2026-03-11',
    services: ['Frameless Shower Doors', 'Contractor Remediation'],
    hardware: ['Chrome hardware', '3/8" glass clips'],
    scenarioType: 'real',
    excerpt: 'An interior design firm\'s previous contractor used the wrong clips, botched the silicone, and ghosted his own warranty. We fixed it — and gained a long-term design partner.',
    image: '/gallery/jakob-interior-design-collaboration-desktop.jpg',
    imageAlt: 'Frameless tub enclosure with chrome hardware against white marble tile — remediated NYC project',
  },
  {
    slug: 'shower-glass-design-consultation-nyc',
    title: 'We Design Before We Install: Shower Glass Consultation for Architects and Designers',
    date: '2026-03-11',
    services: ['Frameless Shower Doors', 'Design Consultation'],
    hardware: ['CRL hinges', 'U-channel', 'Glass-to-glass clamps', 'Barn-door track'],
    scenarioType: 'real',
    excerpt: 'We render multiple enclosure configurations — swing, sliding, fixed panel — in your client\'s actual bathroom with hardware finish comparisons before fabrication begins.',
    image: '/editorial/design-process-sketch.jpg',
    imageAlt: 'Shower glass design sketch showing bathroom configuration renders on tablet with hardware finish annotations',
  },
  {
    slug: 'coop-condo-shower-door-installation-nyc',
    title: 'Co-op & Condo Shower Door Installation in NYC: What You Need to Know',
    date: '2026-03-11',
    services: ['Frameless Shower Doors', 'Building Coordination'],
    hardware: ['Wall-mount hinges', 'U-channel', 'Sleeve anchors'],
    scenarioType: 'real',
    excerpt: 'Everything NYC co-op and condo owners need to know: COI requirements, freight elevator scheduling, quiet hours, alteration agreements, and pre-war building considerations.',
    image: '/editorial/shower-door.jpg',
    imageAlt: 'Frameless shower door installed in a NYC co-op apartment',
  },
  {
    slug: 'single-swing-door-nyc',
    title: 'Single Swing Frameless Shower Door: NYC\'s Most Popular Configuration',
    date: '2026-02-23',
    services: ['Frameless Shower Doors'],
    hardware: ['Wall-mount hinges', 'Pivot hinges'],
    scenarioType: 'real',
    excerpt: 'Why the single swing door is NYC\'s #1 shower configuration — glass thickness, swing direction, and what makes it ideal for apartments.',
    image: '/editorial/configurations/single-swing-door.jpg',
    imageAlt: 'Single swing frameless shower door with satin brass hinges',
  },
  {
    slug: 'door-fixed-panel-nyc',
    title: 'Door + Fixed Panel: The Go-To for Wider NYC Shower Openings',
    date: '2026-02-23',
    services: ['Frameless Shower Doors'],
    hardware: ['Glass-to-glass clamps', 'U-channel', 'Support bar'],
    scenarioType: 'real',
    excerpt: 'When your opening exceeds 36", you need a fixed panel. NYC tub-to-shower conversions, hardware matching, and sizing guide.',
    image: '/editorial/configurations/door-fixed-panel.jpg',
    imageAlt: 'Frameless door plus fixed glass panel with satin brass hardware',
  },
  {
    slug: 'sliding-bypass-doors-nyc',
    title: 'Sliding Bypass Frameless Doors: When There\'s No Room to Swing',
    date: '2026-02-23',
    services: ['Frameless Shower Doors'],
    hardware: ['Barn-door track', 'Top-hung rollers'],
    scenarioType: 'real',
    excerpt: 'Frameless bypass doors for NYC tub-shower combos. Cost vs framed sliders, maintenance tips, and when this is the right choice.',
    image: '/editorial/configurations/sliding-bypass-doors.jpg',
    imageAlt: 'Frameless sliding bypass shower door with satin brass track hardware',
  },
  {
    slug: '90-corner-enclosure-nyc',
    title: '90° Corner Enclosure: The Luxury Standard for NYC Showers',
    date: '2026-02-23',
    services: ['Frameless Shower Doors'],
    hardware: ['Glass-to-glass 90° clamp', 'Wall-mount hinges'],
    scenarioType: 'real',
    excerpt: 'Two glass walls at 90° — the luxury standard. Why corners work in tight NYC bathrooms and what the cost premium looks like.',
    image: '/editorial/configurations/90-corner-enclosure.jpg',
    imageAlt: '90-degree corner frameless glass enclosure with satin brass hinge',
  },
  {
    slug: 'neo-angle-enclosure-nyc',
    title: 'Neo-Angle Enclosure: Solving NYC\'s Odd-Shaped Shower Bases',
    date: '2026-02-23',
    services: ['Frameless Shower Doors'],
    hardware: ['Angled clamps', 'Multi-point connectors'],
    scenarioType: 'real',
    excerpt: 'Built for non-standard and angled bases common in pre-war NYC buildings. How the 3-panel geometry maximizes space.',
    image: '/editorial/configurations/neo-angle-enclosure.jpg',
    imageAlt: 'Neo-angle frameless glass enclosure overhead view with brass clamps',
  },
  {
    slug: 'walk-in-shower-panel-nyc',
    title: 'Walk-In Shower Panel: The Wet Room Look Taking Over NYC',
    date: '2026-02-23',
    services: ['Frameless Shower Doors'],
    hardware: ['Wall clamps'],
    scenarioType: 'real',
    excerpt: 'No door, just a fixed panel. The most premium shower look in NYC — and what waterproofing it requires.',
    image: '/editorial/configurations/walk-in-panel.jpg',
    imageAlt: 'Walk-in frameless glass shower panel with satin brass wall clamps',
  },
  {
    slug: 'typical-mirror-replacement-nyc',
    title: 'Mirror Replacement in a NYC Apartment: What to Expect',
    date: '2026-02-15',
    services: ['Custom Mirrors', 'Mirror Installation'],
    materials: ['1/4" flat polished mirror', 'J-channel mounting'],
    durationRange: '1–2 hours',
    priceRange: '$200–$800',
    scenarioType: 'typical',
    excerpt: 'A walkthrough of what a typical mirror replacement looks like in a New York City apartment — from measurement to install.',
    image: '/gallery/mirror-cabinet-blue-tape.jpg',
    imageAlt: 'Medicine cabinet mirror with blue tape during silicone curing in NYC apartment',
  },
  {
    slug: 'crl-geneva-vs-vienna-hinges',
    title: 'CRL Geneva vs Vienna Hinges: A High-Level Comparison',
    date: '2026-02-18',
    services: ['Frameless Shower Doors'],
    hardware: ['CRL Geneva hinge', 'CRL Vienna hinge'],
    scenarioType: 'real',
    excerpt: 'Two of the most popular frameless shower door hinges compared — when to use each, and why it matters for your installation.',
    image: '/editorial/tools.jpg',
    imageAlt: 'Shower door hardware and installation tools',
  },
]
