export interface Project {
  slug: string
  title: string
  date: string
  borough?: string
  neighborhood?: string
  services: string[]
  materials?: string[]
  hardware?: string[]
  durationRange?: string
  priceRange?: string
  scenarioType: 'real' | 'typical'
  excerpt: string
  image: string
  imageAlt: string
}

export const projects: Project[] = [
  {
    slug: 'frameless-shower-door-cost-nyc',
    title: 'Frameless Shower Door Cost in NYC: What Actually Changes the Price',
    date: '2026-05-09',
    services: ['Frameless Shower Doors', 'Buyer Guide'],
    materials: ['3/8" tempered glass', '1/2" tempered glass'],
    scenarioType: 'typical',
    excerpt: 'A practical buyer guide to NYC frameless shower door pricing, layout choices, hardware, glass thickness, and building coordination.',
    image: '/editorial/configurations/door-fixed-panel.jpg',
    imageAlt: 'Frameless shower door and fixed panel configuration with satin brass hardware',
  },

  {
    slug: 'visualize-shower-door-options-nyc',
    title: 'Compare Shower Door Layout Options Before Ordering Glass',
    date: '2026-04-01',
    services: ['Frameless Shower Doors', 'Design Consultation', 'Neo-Angle Enclosure'],
    materials: ['3/8" clear tempered glass'],
    hardware: ['Chrome sliding hardware', 'Chrome hinges'],
    scenarioType: 'typical',
    excerpt: 'Compare possible shower glass layouts. Photos, field measurements, and hardware constraints determine which options fit a specific bathroom.',
    image: '/gallery/visualize-feature-neo-angle.jpg',
    imageAlt: 'Neo-angle curved frameless shower enclosure with chrome hardware in a compact NYC bathroom with white marble tile',
  },
  {
    slug: '84-clinton-lower-east-side-shower-door-before-after',
    title: '84 Clinton Shower Door Before and After, Lower East Side Manhattan',
    date: '2026-03-16',
    borough: 'Manhattan',
    neighborhood: 'Lower East Side',
    services: ['Sliding Shower Doors', 'Frameless Shower Doors'],
    hardware: ['Chrome sliding hardware', 'Towel bar handles'],
    scenarioType: 'real',
    excerpt: 'A before and after shower door setup at 84 Clinton, Lower East Side Manhattan, showing how a compact bathroom can feel brighter, cleaner, and more finished with a custom sliding glass enclosure.',
    image: '/gallery/84-clinton-after-preview.jpg',
    imageAlt: 'Completed sliding shower door at 84 Clinton in the Lower East Side, Manhattan',
  },
  {
    slug: 'interior-design-collaboration-shower-door-nyc',
    title: 'Why It Matters Who You Hire: A Glass Install Gone Wrong — and How We Fixed It',
    date: '2026-03-11',
    services: ['Frameless Shower Doors', 'Contractor Remediation'],
    hardware: ['Chrome hardware', '3/8" glass clips'],
    scenarioType: 'real',
    excerpt: 'An interior design firm\'s previous contractor used the wrong clips, botched the silicone, and ghosted his own warranty. We fixed it — and gained a long-term design partner.',
    image: '/gallery/jakob-interior-design-collaboration-desktop.jpg',
    imageAlt: 'Frameless tub enclosure with chrome hardware against white marble tile — remediated NYC project',
  },
  {
    slug: 'shower-glass-design-consultation-nyc',
    title: 'Shower Glass Planning for Architects and Designers',
    date: '2026-03-11',
    services: ['Frameless Shower Doors', 'Planning Guide'],
    hardware: ['CRL hinges', 'U-channel', 'Glass-to-glass clamps', 'Barn-door track'],
    scenarioType: 'typical',
    excerpt: 'Questions architects, designers, contractors, and homeowners can resolve before shower glass fabrication, from layout and hardware to field dimensions and building requirements.',
    image: '/editorial/design-process-sketch.jpg',
    imageAlt: 'Shower glass design sketch showing bathroom configuration renders on tablet with hardware finish annotations',
  },
  {
    slug: 'coop-condo-shower-door-installation-nyc',
    title: 'Co-op & Condo Shower Door Installation in NYC: What You Need to Know',
    date: '2026-03-11',
    services: ['Frameless Shower Doors', 'Building Coordination'],
    hardware: ['Wall-mount hinges', 'U-channel', 'Sleeve anchors'],
    scenarioType: 'typical',
    excerpt: 'Everything NYC co-op and condo owners need to know: COI requirements, freight elevator scheduling, quiet hours, alteration agreements, and pre-war building considerations.',
    image: '/editorial/shower-door.jpg',
    imageAlt: 'Frameless shower door installed in a NYC co-op apartment',
  },
  {
    slug: 'single-swing-door-nyc',
    title: 'Single Swing Frameless Shower Door: Layout Guide',
    date: '2026-02-23',
    services: ['Frameless Shower Doors'],
    hardware: ['Wall-mount hinges', 'Pivot hinges'],
    scenarioType: 'typical',
    excerpt: 'A guide to single swing doors, including glass thickness, swing clearance, and apartment layout decisions.',
    image: '/editorial/configurations/single-swing-door.jpg',
    imageAlt: 'Single swing frameless shower door with satin brass hinges',
  },
  {
    slug: 'door-fixed-panel-nyc',
    title: 'Door + Fixed Panel: The Go-To for Wider NYC Shower Openings',
    date: '2026-02-23',
    services: ['Frameless Shower Doors'],
    hardware: ['Glass-to-glass clamps', 'U-channel', 'Support bar'],
    scenarioType: 'typical',
    excerpt: 'A fixed panel can help manage wider openings. Compare layout, hardware, and sizing considerations before choosing a system.',
    image: '/editorial/configurations/door-fixed-panel.jpg',
    imageAlt: 'Frameless door plus fixed glass panel with satin brass hardware',
  },
  {
    slug: 'sliding-bypass-doors-nyc',
    title: 'Sliding Bypass Frameless Doors: When There\'s No Room to Swing',
    date: '2026-02-23',
    services: ['Frameless Shower Doors'],
    hardware: ['Barn-door track', 'Top-hung rollers'],
    scenarioType: 'typical',
    excerpt: 'Frameless bypass doors for NYC tub-shower combos. Cost vs framed sliders, maintenance tips, and when this is the right choice.',
    image: '/editorial/configurations/sliding-bypass-doors.jpg',
    imageAlt: 'Frameless sliding bypass shower door with satin brass track hardware',
  },
  {
    slug: '90-corner-enclosure-nyc',
    title: '90° Corner Enclosure: Layout and Cost Considerations',
    date: '2026-02-23',
    services: ['Frameless Shower Doors'],
    hardware: ['Glass-to-glass 90° clamp', 'Wall-mount hinges'],
    scenarioType: 'typical',
    excerpt: 'How a 90° corner enclosure can work in some layouts, with more glass, hardware, and installation factors to price.',
    image: '/editorial/configurations/90-corner-enclosure.jpg',
    imageAlt: '90-degree corner frameless glass enclosure with satin brass hinge',
  },
  {
    slug: 'neo-angle-enclosure-nyc',
    title: 'Neo-Angle Enclosure: Solving NYC\'s Odd-Shaped Shower Bases',
    date: '2026-02-23',
    services: ['Frameless Shower Doors'],
    hardware: ['Angled clamps', 'Multi-point connectors'],
    scenarioType: 'typical',
    excerpt: 'Built for non-standard and angled bases common in pre-war NYC buildings. How the 3-panel geometry maximizes space.',
    image: '/editorial/configurations/neo-angle-enclosure.jpg',
    imageAlt: 'Neo-angle frameless glass enclosure overhead view with brass clamps',
  },
  {
    slug: 'walk-in-shower-panel-nyc',
    title: 'Walk-In Shower Panel: Layout and Water Control',
    date: '2026-02-23',
    services: ['Frameless Shower Doors'],
    hardware: ['Wall clamps'],
    scenarioType: 'typical',
    excerpt: 'A fixed panel without a door can create an open look when the layout and waterproofing can control water.',
    image: '/editorial/configurations/walk-in-panel.jpg',
    imageAlt: 'Walk-in frameless glass shower panel with satin brass wall clamps',
  },
  {
    slug: 'typical-mirror-replacement-nyc',
    title: 'Mirror Replacement in a NYC Apartment: What to Expect',
    date: '2026-02-15',
    services: ['Custom Mirrors', 'Mirror Installation'],
    materials: ['1/4" flat polished mirror', 'J-channel mounting'],
    scenarioType: 'typical',
    excerpt: 'Plan a mirror replacement around the wall, mounting, edge finish, removal, and building access before requesting a quote.',
    image: '/gallery/mirror-cabinet-blue-tape.jpg',
    imageAlt: 'Mirror panel held with blue tape during adhesive curing',
  },
  {
    slug: 'crl-geneva-vs-vienna-hinges',
    title: 'CRL Geneva vs Vienna Hinges: A High-Level Comparison',
    date: '2026-02-18',
    services: ['Frameless Shower Doors'],
    hardware: ['CRL Geneva hinge', 'CRL Vienna hinge'],
    scenarioType: 'typical',
    excerpt: 'Compare two frameless shower door hinge options and the specifications to confirm before installation.',
    image: '/editorial/tools.jpg',
    imageAlt: 'Shower door hardware and installation tools',
  },
]
